name: Basic Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()

  unittest:
    name: Unit test - ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - py311
          - py312
          - py313
          - py314
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          run-install: false
          post-cleanup: false
      - name: Apply workarounds
        run: |
          # Workaround for https://github.com/prefix-dev/pixi/issues/3762
          sed -i.bak 's@editable = true@editable = false@g' pyproject.toml
          rm pyproject.toml.bak
          # Show any changes
          git diff
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          cache: false
          environments: ${{ matrix.python-version }}
      - name: Run pytest
        run: pixi run -e ${{ matrix.python-version }} pytest


  perftest:
    name: Perf test - ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - py311
          - py312
          - py313
          - py314
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          run-install: false
          post-cleanup: false
      - name: Apply workarounds
        run: |
          # Workaround for https://github.com/prefix-dev/pixi/issues/3762
          sed -i.bak 's@editable = true@editable = false@g' pyproject.toml
          rm pyproject.toml.bak
          # Show any changes
          git diff
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          cache: false
          environments: ${{ matrix.python-version }}
      - name: Run pytest
        run: pixi run -e ${{ matrix.python-version }} benchmark --test-results-dir ${{ runner.temp }}/perf_tests/
      - name: Upload perf test result
        uses: actions/upload-artifact@v6
        with:
          name: perf-results-${{ matrix.python-version }}
          path: ${{ runner.temp }}/perf_tests/*

  compare-perf:
    name: Compare perf results
    needs: perftest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v7
        with:
          path: ${{ runner.temp }}/perf_tests/
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R ${{ runner.temp }}/perf_tests/
      - name: display content
        run: find ${{ runner.temp }}/perf_tests/ -name '*json' -exec cat {} \;
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          run-install: false
          post-cleanup: false
      - name: Apply workarounds
        run: |
          # Workaround for https://github.com/prefix-dev/pixi/issues/3762
          sed -i.bak 's@editable = true@editable = false@g' pyproject.toml
          rm pyproject.toml.bak
          # Show any changes
          git diff
      - name: Compare tests
        run: |
          pixi run -e py314 display-benchmark-comparison --test-results-dir ${{ runner.temp }}/perf_tests/ --md-output ${{ runner.temp }}/perf_tests/pretty.md
      - name: Create Comment
        if: ${{ github.event_name == 'pull_request' }}
        run:
          gh pr comment $PRNUM --body-file ${{ runner.temp }}/perf_tests/pretty.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number }}

  # run-profiling:
  #   name: Profile presigned URLs
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v6
  #     - name: Apply workarounds
  #       run: |
  #         # Workaround for https://github.com/prefix-dev/pixi/issues/3762
  #         sed -i.bak 's@editable = true@editable = false@g' pyproject.toml
  #         rm pyproject.toml.bak
  #         # Show any changes
  #         git diff
  #     - uses: prefix-dev/setup-pixi@v0.9.3
  #       with:
  #         environment: py314
  #     - name: Run pytest
  #       run: pixi run -e py314 pytest -v -s profiling_tests/test_profile.py --test-results-dir ${{ runner.temp }}/profiling/
  #     - name: Generate table
  #       shell: pixi run -e py314 bash -e {0}
  #       run: |
  #         python -c "import pstats;from pstats import SortKey; pstats.Stats('${{ runner.temp }}/profiling/profile_generate_presigned_post/presigned_post.prof').sort_stats(SortKey.TIME).print_stats(10)" > ${{ runner.temp }}/profiling/presigned_post.md
  #     # - name: Upload profiling SVG
  #     #   uses: actions/upload-artifact@v6
  #     #   with:
  #     #     name: profiling-flamegraph
  #     #     path: ${{ runner.temp }}/profiling/presigned_post.svg
  #     - name: Create Comment
  #       if: ${{ github.event_name == 'pull_request' }}
  #       run: |
  #         gh pr comment $PRNUM --body-file ${{ runner.temp }}/profiling/presigned_post.md
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GH_REPO: ${{ github.repository }}
  #         PRNUM: ${{ github.event.pull_request.number }}
